### ISSUE TITLE
Maven central publishing

### ISSUE THREAD

**Issue by nicolas-vivot** [quarkiverse/quarkus-datadog-opentracing#12]
Hi @gastaldi 

Sorry to bother you again.

I've made a first release (1.0.0), but cannot find it on the maven central.

When comparing build traces from other projects i noticed that they upload on the repository ioquarkiverse-1177 while my project is uploading to ioquarkiverse-1007.

I checked again the [release documentation](https://quarkus.io/blog/quarkiverse/) and found something i did not realize before, this 'Release on Quarkiverse' Option when Merging the branch having the changes on the project yaml file.

I run again a pull request to check the options i have, and could not find it:
![image](https://user-images.githubusercontent.com/79290619/116637237-4c99b200-a99e-11eb-9f18-e4403813a0ca.png)

Did i miss something ?

**Comment by gastaldi** [comment]
@nicolas-vivot you did all correctly. I can see 1.0.0 in https://repo1.maven.org/maven2/io/quarkiverse/opentracing/datadog/quarkus-datadog-opentracing/1.0.0/

It takes some minutes to reach central after the release, so don't worry 😉

**Comment by gastaldi** [comment]
Btw that `Release on Quarkiverse` green button in the blog isn't real, just a photoshopped image which now I see it caused more confusion :)
