### ISSUE TITLE
Fixing Quarkus Snapshot build

### ISSUE THREAD

**Issue by nicolas-vivot** [quarkiverse/quarkus-datadog-opentracing#7]
Hi @gastaldi 

I would like your insights about the reason why this [Quarkus Snapshot build](https://github.com/quarkiverse/quarkus-datadog-opentracing/actions/runs/794933836) keep failing with this error:
`./ecosystem-ci/setup-and-test: line 4: cd: ecosystem-ci/quarkus-datadog-opentracing: No such file or directory`

As i'm new i read the [documentation](https://github.com/quarkusio/quarkus-ecosystem-ci) and i guess you already setup everything.

**Comment by gastaldi** [comment]
@nicolas-vivot oops, my fault. I provided a PR that fixes that. Sorry for the trouble

**Comment by nicolas-vivot** [comment]
No worries :)

I double checked the config files and did not see the name was wrong, thank you !
